ifeq ($(FEATURE_DELETE_UNIQUE_NAME_DEVICE), y)
CFLAGS	+= -DFEATURE_DELETE_UNIQUE_NAME_DEVICE
endif

ifeq ($(FEATURE_DELETE_UNIQUE_DATA_NAME_POINT), y)
CFLAGS	+= -DFEATURE_DELETE_UNIQUE_DATA_NAME_POINT
endif

ifeq ($(FEATURE_BEFORE_PARSE_CONFIG_DELETE_CACHE), y)
CFLAGS	+= -DFEATURE_BEFORE_PARSE_CONFIG_DELETE_CACHE
endif

ifeq ($(FEATURE_FILE_LOG), y)
CFLAGS	+= -DFEATURE_FILE_LOG
endif

ifeq ($(FEATURE_USE_UNIX_SOCKET_CONNECT_REDIS), y)
CFLAGS	+= -DFEATURE_USE_UNIX_SOCKET_CONNECT_REDIS
endif

